// GENERATED by scripts/sync-tokens.mjs from wadzzoAR/src/styles/arcade.css.
// Do not edit by hand — change the web palette and re-run the script.

export type Rgb = readonly [number, number, number];
export type TokenName =
  | "ar-void"
  | "ar-bg"
  | "ar-surface"
  | "ar-surface-2"
  | "ar-surface-3"
  | "ar-line"
  | "ar-line-bright"
  | "ar-text"
  | "ar-text-dim"
  | "ar-text-faint"
  | "ar-green"
  | "ar-green-hot"
  | "ar-green-deep"
  | "ar-green-ink"
  | "rarity-common"
  | "rarity-rare"
  | "rarity-epic"
  | "rarity-legendary"
  | "rarity-mythic"
  | "ar-danger"
  | "ar-locked";

export const palettes: Record<"light" | "dark", Record<TokenName, Rgb>> = {
  light: {
    "ar-void": [245, 249, 247],
    "ar-bg": [240, 245, 241],
    "ar-surface": [255, 255, 255],
    "ar-surface-2": [243, 246, 244],
    "ar-surface-3": [230, 234, 231],
    "ar-line": [207, 216, 210],
    "ar-line-bright": [171, 186, 176],
    "ar-text": [16, 30, 23],
    "ar-text-dim": [66, 87, 77],
    "ar-text-faint": [108, 127, 117],
    "ar-green": [22, 108, 19],
    "ar-green-hot": [17, 91, 11],
    "ar-green-deep": [25, 87, 25],
    "ar-green-ink": [244, 250, 244],
    "rarity-common": [83, 101, 110],
    "rarity-rare": [12, 107, 151],
    "rarity-epic": [122, 45, 190],
    "rarity-legendary": [142, 94, 11],
    "rarity-mythic": [184, 30, 128],
    "ar-danger": [184, 30, 35],
    "ar-locked": [96, 104, 118],
  },
  dark: {
    "ar-void": [5, 10, 8],
    "ar-bg": [10, 16, 13],
    "ar-surface": [19, 27, 23],
    "ar-surface-2": [29, 38, 33],
    "ar-surface-3": [40, 51, 46],
    "ar-line": [54, 69, 62],
    "ar-line-bright": [75, 99, 88],
    "ar-text": [243, 246, 245],
    "ar-text-dim": [167, 180, 173],
    "ar-text-faint": [108, 122, 115],
    "ar-green": [63, 216, 49],
    "ar-green-hot": [108, 246, 81],
    "ar-green-deep": [30, 116, 27],
    "ar-green-ink": [4, 37, 4],
    "rarity-common": [150, 162, 166],
    "rarity-rare": [44, 202, 242],
    "rarity-epic": [173, 97, 239],
    "rarity-legendary": [251, 186, 35],
    "rarity-mythic": [246, 81, 191],
    "ar-danger": [228, 78, 83],
    "ar-locked": [113, 119, 132],
  },
};

export const radii = {
  "ar-sm": 10,
  "ar": 16,
  "ar-lg": 22,
  "ar-xl": 30
} as const;
